### ISSUE TITLE
output does not match input data

### ISSUE THREAD

**Issue by MeiShu00** [cytham/nanovar#35]
Hi,

I recently tried NanoVar on 1D Nanopore data for targeted sequencing of a few STR loci. I am able to view these reads that overlap the STR loci on IGV but NanoVar is unable to report anything in these STR loci. My read depth is ~0.1X but i'm not sure if this is the reason as NanoVar called insertion in other chromosomes with supporting reads count as low as 2 reads when i have >500,000 reads in one of the STR loci. 

Hence, I would like to check what could be the reason for no variant detection in those STR loci. 
Also, may i know what is meant by BND SVs and how to interpret SVLEN=>326 in the vcf file? 

Thank you !

**Comment by cytham** [comment]
Hi @MeiShu00,

Thanks for trying out NanoVar. 

Do you expect to see SVs in these STR loci? If so, can you send me a IGV snapshot of such loci which shows read alignment abnormalities that imply an SV?

Read depth might not be a problem for NanoVar to call variants in the targeted loci.

BND refers to breakend SVs which represent either a translocation breakpoint or a genomic sequence transposition breakpoint (or interspersed duplication). There is a SV2 column in the INFO which tells you whether the SV is a TLO (translocation) or a TPO (transposition). You can check out the wiki [here](https://github.com/cytham/nanovar/wiki/Output). Also check out [here](https://samtools.github.io/hts-specs/VCFv4.2.pdf) for more information about breakends.

SVLEN=>326 can be interpreted as an SV having a length of more or equal to 326 bp. NanoVar is uncertain because there is insufficient information in the reads to define the full length of the SV.

**Comment by MeiShu00** [comment]
Hi cytham,

Thank you for your speedy reply, below is a screenshot of IGV for chr11:4890980-4891026 of motif (AAT)n: 
![image](https://user-images.githubusercontent.com/69883139/134645834-386c6da7-75ed-413b-bbdb-8e1dac1fbdb4.png)

**Comment by cytham** [comment]
Hi @MeiShu00,

The snapshot looks like there is an insertion (probably varying lengths of (AAT)n like you said). However, as these insertions are small (less than 25 bp), they are not picked up by NanoVar. NanoVar was developed to detect SVs which are >50bp in size, so I believe it will not detect your small indels efficiently. 

You might want to try running NanoVar with a smaller length threshold using the --minlen option (E.g. --minlen 5), but I am not sure if that will work or it might even break the program, resulting in high false positives.

**Comment by MeiShu00** [comment]
Hi @cytham,

I see! I will try running NanoVar with a smaller length threshold. 
Thank you !
