### ISSUE TITLE
Workflow failing due to makeblastdb and hs-blastn

### ISSUE THREAD

**Issue by lisosome** [cytham/nanovar#62]
Hi!
I've been trying to run nanovar to detect SVs and CNVs from a low coverage run on minION. However, the workflows fails due to makeblastdb and, subsequently, hs-blastn. Nanovar (v1.4.1) has been installed via pip and the dependencies have been built following the instructions on the github page. 

Here's the nanovar log:
[NanoVar-010823-1939.log](https://github.com/cytham/nanovar/files/12237212/NanoVar-010823-1939.log)

Here's the code I've been using:
`inbam=$1
workdir=$2

module load conda samtools bedtools2
conda activate nanovar

minimap=/orfeo/cephfs/home/burlo/nardone/.conda/envs/minimap2/bin/minimap2
makeblastdb=/orfeo/cephfs/home/burlo/nardone/software/blast/ncbi-blast-2.3.0+/bin/makeblastdb
hsblastn=/orfeo/cephfs/home/burlo/nardone/software/blast/queries/hs-blastn-src/v0.0.5/hs-blastn
windowmsk=/orfeo/cephfs/home/burlo/nardone/software/blast/ncbi-blast-2.3.0+/bin/windowmasker

nanovar -x ont -t 24 -f hg38 --force --cnv hg38 --mm ${minimap} --mdb ${makeblastdb} --wmk ${windowmsk} --hsb ${hsblastn} ${inbam}  /fast/burlo/fcrudele/resources/hgRef/GRCh38.p13/no_alt/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna ${workdir}`

Thanks!

**Comment by cytham** [comment]
@lisosome Looks like you are missing the libnsl.so.1 shared library
```/orfeo/cephfs/home/burlo/nardone/software/blast/ncbi-blast-2.3.0+/bin/makeblastdb: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory``` 
You may want to look it up online to get the library.

Two things to note:
1) We are making some changes to the algorithm within NanoVar and will release a new version soon. This new version wouldn't need hsblastn so that would make things easier for you. You may want to wait for this version.
2) The --cnv option is still underdeveloped and I would not recommend using it. It will be temporary removed in the newer version until further notice. Meanwhile I would recommend you to use the the CNV workflow from https://github.com/epi2me-labs/wf-human-variation instead.

Thank you

**Comment by lisosome** [comment]
@cytham  Thank you very much! 
Looks like I've missed that row reading the log file. I'm closing the issue.

Thanks again!
